config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[ show ]

  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save!
    redirect_to flat_path(@flat)
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1 class="text-center">All flats</h1>

<div class="row justify-content-center">
<% @flats.each do |flat| %>
  <div class="card m-3" style="width: 18rem;">
  <img class="card-img-top" src="https://mir-s3-cdn-cf.behance.net/project_modules/1400/8bc05981988591.5d107cb99ca6c.jpg" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><%= flat.name %></h5>
    <p class="card-text"> <em><%= flat.address %></em> </p>
    <p class="card-text"><%= flat.price_per_night %> €</p>
    <p class="card-text"><%= flat.description %></p>
    <button class="btn btn-warning"><%= link_to "En savoir plus", flat_path(flat) %></button>

  </div>
</div>
<% end %>
</div>

app/views/flats/new.html.erb
<div class="container">
<%= link_to "HOME", flats_path %>
  <h1>New review</h1>
  <%= simple_form_for [@flat] do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
     <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.submit "Submit review", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/flats/show.html.erb
<div class="container">
  <%= link_to "HOME", flats_path %>
  <h1><%= @flat.name %></h1>

  <h6>Adress: <%= @flat.address %></h6>
  <h6>Phone: <%= @flat.description %></h6>
  <h6>Category: <%= @flat.price_per_night %></h6>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
  <div><%= link_to "Add a new flat", new_flat_path %></div>
    <%= yield %>
  </body>
</html>